app/models/personaje.py
class Personaje:
    def __init__(self, id, name,status,gender,image):
        self.id = id
        self.name = name
        self.status = status
        self.gender = gender
        self.image = image

    def to_json(self):
        return {
            'id' : self.id,
            'name' : self.name,
            'status' : self.status,
            'gender' : self.gender,
            'image' : self.image
            }

app/models/rick_y_morty.py
class Personajes:
    def __init__(self, id, name,status,gender,image):
        self.id = id
        self.name = name
        self.status = status
        self.gender = gender
        self.image = image

    def to_json(self):
        return {
            'id' : self.id,
            'name' : self.name,
            'status' : self.status,
            'gender' : self.gender,
            'image' : self.image
            }

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, DateField, IntegerField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class LibroForm(FlaskForm):
    title = StringField('Title:', validators=[DataRequired()])
    author = StringField('Author:', validators=[DataRequired()])
    pages = IntegerField ('Pages:', validators=[DataRequired()])
    publish_date = DateField('Publish Date:', validators=[DataRequired()])
    description = TextAreaField('Description:', validators=[DataRequired()])
    isbn = StringField('ISBN:', validators=[DataRequired()])
    button = SubmitField('Create Book')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from .config import Config
from .routes.rick_y_morty import rick_y_morty

def create_app():
    app= Flask(__name__)
    app.config.from_object(Config)

    Bootstrap(app)

    app.register_blueprint(blueprint=rick_y_morty)
    # SQLAlchemy(app)
    # Moment(app)
    return app

app/routes/rick_y_morty.py
from flask import Blueprint, render_template, redirect,url_for
from app.models.personaje import Personaje
from app.db import db
from app.requests import Request


rick_y_morty = Blueprint('rick_y_morty', __name__)


@rick_y_morty.route('/', methods=['GET'])
def index():
    personajes = db.personajes.find()
    return render_template('index.html',personajes=personajes)


@rick_y_morty.route('/insertar-personaje', methods = ['GET', 'POST'])
def insertar_personaje():
    personajes = Request().characters()
    db.personajes.insert_many(personajes)
    return 'PERSONAJES INSERTADOS!'


@rick_y_morty.route('/profile', defaults = {'id': None})
@rick_y_morty.route('/profile/', defaults = {'id': None})
@rick_y_morty.route('/profile/<int:id>')
def profile(id = None):
    if id == None:
        return redirect('/')
    personaje = db.personajes.find_one({'id':int(id)})
    if personaje == None:
        return redirect('/')
    return render_template("profile.html",personaje=personaje)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block body %}
  <div class="container">
    {% for message in get_flashed_messages(category_filter=['success']) %}
    <div class="alert alert-success alert-dismissible">
      <button class="close" data-dismiss="alert">&times;</button>
      {{ message }}
    </div>
    {% endfor %} 
    
    {% for message in get_flashed_messages(category_filter=['error'])%}
    <div class="alert alert-danger alert-dismissible">
      <button class="close" data-dismiss="alert">&times;</button>
      {{ message }}
    </div>
    {% endfor %} {% block content %} {% endblock %}
  </div>

  {% block scripts %} {{ super() }}

{% endblock %} 

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

{% block content %}

<h1>Rick y Morty API</h1>

<div class="container">
    <p> ¡Da click en cualquier imagen!</p>
    {% for personaje in personajes %}
        <a href="{{ url_for('rick_y_morty.profile',id=personaje['id']) }}">
            <img src="{{ personaje['image'] }}" 
            alt="{{ personaje['name'] }}, a character from Rick and Morty">
        </a>
        <p>Nombre: {{personaje['name']}}</p>
        <p>Estado: {{personaje['status']}}</p>
        <p>Género: {{personaje['gender']}}</p>
    {% endfor %}

</div>


{% endblock content %}

app/templates/profile.html
{% extends 'base.html' %}

{% block content %}

<h1>Character Profile</h1>

<div class="container">
    <div class="container-character">
        <img src="{{ personaje['image'] }}" alt = "Character image">
        <p>Nombre: {{ personaje['name'] }}</p>
        <p>Estado: {{ personaje['status'] }}</p>
        <p>Género: {{ personaje['gender'] }}</p>
    </div>
    <a href="{{ url_for('rick_y_morty.index') }}">Back to main page</a>
</div>

{% endblock content %}